import {
  IconAddressBook,
  IconApps,
  IconArrowLeft,
  IconBackpack,
  IconBell,
  IconBrandGmail,
  IconBrandInstagram,
  IconBriefcase,
  IconBuilding,
  IconBuildingBank,
  IconCash,
  IconChartBar,
  IconChartDots,
  IconCheck,
  IconChecklist,
  IconChevronDown,
  IconChevronRight,
  IconClipboardList,
  IconCloud,
  IconCode,
  IconCoin,
  IconCoins,
  IconDeviceDesktop,
  IconEye,
  IconFileDescription,
  IconFileInvoice,
  IconFlag,
  IconFlask,
  IconFolders,
  IconGlobe,
  IconHeartHandshake,
  IconHistory,
  IconInfoCircle,
  IconLayoutGrid,
  IconListDetails,
  IconLogout2,
  IconMail,
  IconMailOpened,
  IconMenu2,
  IconMinus,
  IconPackage,
  IconPlugConnected,
  IconPlugConnectedX,
  IconReceiptTax,
  IconRefresh,
  IconRocket,
  IconScale,
  IconSchool,
  IconServer,
  IconShare,
  IconStereoGlasses,
  IconSun,
  IconTarget,
  IconTimeline,
  IconTools,
  IconTrendingDown,
  IconTrendingUp,
  IconUserCheck,
  IconUserCircle,
  IconUserStar,
  IconUsers,
  IconUsersGroup,
  IconWorld,
  IconX,
  type Icon as TablerIcon,
  type IconProps as TablerIconProps,
} from "@tabler/icons-react";

const ICONS: Record<string, TablerIcon> = {
  "ti-address-book": IconAddressBook,
  "ti-apps": IconApps,
  "ti-arrow-left": IconArrowLeft,
  "ti-bell": IconBell,
  "ti-brand-gmail": IconBrandGmail,
  "ti-brand-instagram": IconBrandInstagram,
  "ti-briefcase": IconBriefcase,
  "ti-building": IconBuilding,
  "ti-building-bank": IconBuildingBank,
  "ti-cash": IconCash,
  "ti-chart-bar": IconChartBar,
  "ti-chart-dots": IconChartDots,
  "ti-check": IconCheck,
  "ti-checklist": IconChecklist,
  "ti-chevron-down": IconChevronDown,
  "ti-chevron-right": IconChevronRight,
  "ti-clipboard-list": IconClipboardList,
  "ti-cloud": IconCloud,
  "ti-code": IconCode,
  "ti-coin": IconCoin,
  "ti-coins": IconCoins,
  "ti-device-desktop": IconDeviceDesktop,
  "ti-device-vr": IconStereoGlasses,
  "ti-eye": IconEye,
  "ti-file-description": IconFileDescription,
  "ti-file-invoice": IconFileInvoice,
  "ti-flag": IconFlag,
  "ti-flask": IconFlask,
  "ti-folders": IconFolders,
  "ti-globe": IconGlobe,
  "ti-graduation-cap": IconBackpack,
  "ti-handshake": IconHeartHandshake,
  "ti-history": IconHistory,
  "ti-info-circle": IconInfoCircle,
  "ti-layout-grid": IconLayoutGrid,
  "ti-list-details": IconListDetails,
  "ti-logout-2": IconLogout2,
  "ti-mail": IconMail,
  "ti-mail-opened": IconMailOpened,
  "ti-menu-2": IconMenu2,
  "ti-minus": IconMinus,
  "ti-package": IconPackage,
  "ti-plug-connected": IconPlugConnected,
  "ti-plug-connected-x": IconPlugConnectedX,
  "ti-receipt-tax": IconReceiptTax,
  "ti-refresh": IconRefresh,
  "ti-rocket": IconRocket,
  "ti-scale": IconScale,
  "ti-school": IconSchool,
  "ti-server": IconServer,
  "ti-share": IconShare,
  "ti-sun": IconSun,
  "ti-target": IconTarget,
  "ti-timeline": IconTimeline,
  "ti-tools": IconTools,
  "ti-trending-down": IconTrendingDown,
  "ti-trending-up": IconTrendingUp,
  "ti-user-check": IconUserCheck,
  "ti-user-circle": IconUserCircle,
  "ti-user-star": IconUserStar,
  "ti-users": IconUsers,
  "ti-users-group": IconUsersGroup,
  "ti-world": IconWorld,
  "ti-x": IconX,
};

type IconProps = {
  name: string;
  className?: string;
} & Omit<TablerIconProps, "className">;

export function Icon({ name, className = "", ...rest }: IconProps) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  // size-[1em] ties the icon's pixel size to the inherited/declared font-size,
  // matching how the original icon-font markup (font-size driven) was authored.
  return <Cmp className={`size-[1em] shrink-0 ${className}`} stroke={1.75} aria-hidden="true" {...rest} />;
}
