import {
  IconActivity,
  IconAddressBook,
  IconAlertCircle,
  IconApps,
  IconArrowLeft,
  IconArrowsHorizontal,
  IconBackpack,
  IconBell,
  IconBook2,
  IconBrandFacebook,
  IconBrandGmail,
  IconBrandGoogleDrive,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTiktok,
  IconBrandTrello,
  IconBriefcase,
  IconBuilding,
  IconBulb,
  IconBuildingBank,
  IconBuildingCommunity,
  IconCash,
  IconCashBanknote,
  IconCashOff,
  IconCertificate,
  IconChalkboard,
  IconChartBar,
  IconChartDots,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChecklist,
  IconChevronDown,
  IconChevronRight,
  IconClipboardList,
  IconClock,
  IconCloud,
  IconCloudComputing,
  IconCode,
  IconCoin,
  IconCoins,
  IconDeviceDesktop,
  IconDiscount,
  IconEye,
  IconFileAlert,
  IconFileDescription,
  IconFileDollar,
  IconFileInvoice,
  IconFlag,
  IconFlask,
  IconFolders,
  IconGauge,
  IconGavel,
  IconGlobe,
  IconHeartHandshake,
  IconHistory,
  IconInbox,
  IconInfoCircle,
  IconLayout,
  IconLayoutGrid,
  IconLibrary,
  IconListDetails,
  IconLock,
  IconLogout2,
  IconMail,
  IconMailOpened,
  IconMenu2,
  IconMinus,
  IconPackage,
  IconPencil,
  IconPhoto,
  IconPhotoVideo,
  IconPlayerPlay,
  IconPlugConnected,
  IconPlugConnectedX,
  IconPlus,
  IconReceiptTax,
  IconRefresh,
  IconReportMoney,
  IconRocket,
  IconRoute,
  IconScale,
  IconSchool,
  IconSearch,
  IconServer,
  IconServer2,
  IconShare,
  IconShieldLock,
  IconSignature,
  IconStar,
  IconStarFilled,
  IconStereoGlasses,
  IconSun,
  IconTarget,
  IconTemplate,
  IconTimeline,
  IconTools,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTrophy,
  IconUserCheck,
  IconUserCircle,
  IconUserPlus,
  IconUserSquareRounded,
  IconUserStar,
  IconUsers,
  IconUsersGroup,
  IconWallet,
  IconWorld,
  IconX,
  type Icon as TablerIcon,
  type IconProps as TablerIconProps,
} from "@tabler/icons-react";

const ICONS: Record<string, TablerIcon> = {
  "ti-activity": IconActivity,
  "ti-address-book": IconAddressBook,
  "ti-alert-circle": IconAlertCircle,
  "ti-apps": IconApps,
  "ti-arrow-left": IconArrowLeft,
  "ti-arrows-horizontal": IconArrowsHorizontal,
  "ti-backpack": IconBackpack,
  "ti-bell": IconBell,
  "ti-book-2": IconBook2,
  "ti-brand-facebook": IconBrandFacebook,
  "ti-brand-gmail": IconBrandGmail,
  "ti-brand-google-drive": IconBrandGoogleDrive,
  "ti-brand-instagram": IconBrandInstagram,
  "ti-brand-linkedin": IconBrandLinkedin,
  "ti-brand-tiktok": IconBrandTiktok,
  "ti-brand-trello": IconBrandTrello,
  "ti-briefcase": IconBriefcase,
  "ti-building": IconBuilding,
  "ti-building-bank": IconBuildingBank,
  "ti-building-community": IconBuildingCommunity,
  "ti-bulb": IconBulb,
  "ti-cash": IconCash,
  "ti-cash-banknote": IconCashBanknote,
  "ti-cash-off": IconCashOff,
  "ti-certificate": IconCertificate,
  "ti-chalkboard": IconChalkboard,
  "ti-chart-bar": IconChartBar,
  "ti-chart-dots": IconChartDots,
  "ti-chart-line": IconChartLine,
  "ti-chart-pie": IconChartPie,
  "ti-check": IconCheck,
  "ti-checklist": IconChecklist,
  "ti-chevron-down": IconChevronDown,
  "ti-chevron-right": IconChevronRight,
  "ti-clipboard-list": IconClipboardList,
  "ti-clock": IconClock,
  "ti-cloud": IconCloud,
  "ti-cloud-computing": IconCloudComputing,
  "ti-code": IconCode,
  "ti-coin": IconCoin,
  "ti-coins": IconCoins,
  "ti-device-desktop": IconDeviceDesktop,
  "ti-device-vr": IconStereoGlasses,
  "ti-discount": IconDiscount,
  "ti-eye": IconEye,
  "ti-file-alert": IconFileAlert,
  "ti-file-description": IconFileDescription,
  "ti-file-dollar": IconFileDollar,
  "ti-file-invoice": IconFileInvoice,
  "ti-flag": IconFlag,
  "ti-flask": IconFlask,
  "ti-folders": IconFolders,
  "ti-gauge": IconGauge,
  "ti-gavel": IconGavel,
  "ti-globe": IconGlobe,
  "ti-graduation-cap": IconBackpack,
  "ti-handshake": IconHeartHandshake,
  "ti-heart-handshake": IconHeartHandshake,
  "ti-history": IconHistory,
  "ti-inbox": IconInbox,
  "ti-info-circle": IconInfoCircle,
  "ti-layout": IconLayout,
  "ti-layout-grid": IconLayoutGrid,
  "ti-library": IconLibrary,
  "ti-list-details": IconListDetails,
  "ti-lock": IconLock,
  "ti-logout-2": IconLogout2,
  "ti-mail": IconMail,
  "ti-mail-opened": IconMailOpened,
  "ti-menu-2": IconMenu2,
  "ti-minus": IconMinus,
  "ti-package": IconPackage,
  "ti-pencil": IconPencil,
  "ti-photo": IconPhoto,
  "ti-photo-video": IconPhotoVideo,
  "ti-player-play": IconPlayerPlay,
  "ti-plug-connected": IconPlugConnected,
  "ti-plug-connected-x": IconPlugConnectedX,
  "ti-plus": IconPlus,
  "ti-receipt-tax": IconReceiptTax,
  "ti-refresh": IconRefresh,
  "ti-report-money": IconReportMoney,
  "ti-rocket": IconRocket,
  "ti-route": IconRoute,
  "ti-scale": IconScale,
  "ti-school": IconSchool,
  "ti-search": IconSearch,
  "ti-server": IconServer,
  "ti-server-2": IconServer2,
  "ti-share": IconShare,
  "ti-shield-lock": IconShieldLock,
  "ti-signature": IconSignature,
  "ti-star": IconStar,
  "ti-star-filled": IconStarFilled,
  "ti-sun": IconSun,
  "ti-target": IconTarget,
  "ti-template": IconTemplate,
  "ti-timeline": IconTimeline,
  "ti-tools": IconTools,
  "ti-trash": IconTrash,
  "ti-trending-down": IconTrendingDown,
  "ti-trending-up": IconTrendingUp,
  "ti-trophy": IconTrophy,
  "ti-user-check": IconUserCheck,
  "ti-user-circle": IconUserCircle,
  "ti-user-plus": IconUserPlus,
  "ti-user-square-rounded": IconUserSquareRounded,
  "ti-user-star": IconUserStar,
  "ti-users": IconUsers,
  "ti-users-group": IconUsersGroup,
  "ti-wallet": IconWallet,
  "ti-world": IconWorld,
  "ti-x": IconX,
};

type IconProps = {
  name: string;
  className?: string;
} & Omit<TablerIconProps, "className">;

export function Icon({ name, className = "", ...rest }: IconProps) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  // size-[1em] ties the icon's pixel size to the inherited/declared font-size,
  // matching how the original icon-font markup (font-size driven) was authored.
  return <Cmp className={`size-[1em] shrink-0 ${className}`} stroke={1.75} aria-hidden="true" {...rest} />;
}
